# aks module implementation
module "aks" {

  source                               = "Azure/aks/azurerm"
  version                              = "10.1.0"
  depends_on                           = [azurerm_resource_group.aks_rg]
  prefix                               = "aks-${local.name_prefix}"
  ebpf_data_plane                      = var.ebpf_data_plane
  resource_group_name                  = azurerm_resource_group.aks_rg.name
  cluster_name                         = local.cluster_name
  location                             = var.location
  role_based_access_control_enabled    = var.role_based_access_control_enabled
  tags                                 = var.default_tags
  kubernetes_version                   = var.kubernetes_version
  orchestrator_version                 = var.kubernetes_version
  network_plugin                       = var.network_plugin
  network_policy                       = var.network_policy
  oidc_issuer_enabled                  = var.oidc_issuer_enabled
  enable_auto_scaling                  = var.enable_auto_scaling
  agents_availability_zones            = var.agents_availability_zones
  temporary_name_for_rotation          = var.temporary_name_for_rotation
  agents_tags                          = var.default_tags
  cluster_log_analytics_workspace_name = local.cluster_name
  agents_pool_name                     = var.agents_pool_name
  agents_labels                        = var.agents_labels
  agents_type                          = var.agents_type
  agents_count                         = var.agents_count
  agents_min_count                     = var.agents_min_count
  agents_max_count                     = var.agents_max_count
  agents_size                          = var.agents_size
  log_analytics_workspace_enabled      = var.log_analytics_workspace_enabled
  image_cleaner_enabled                = var.image_cleaner_enabled
  image_cleaner_interval_hours         = var.image_cleaner_interval_hours
  key_vault_secrets_provider_enabled   = var.key_vault_secrets_provider_enabled
  automatic_channel_upgrade            = var.automatic_channel_upgrade
  identity_type                        = var.identity_type
  net_profile_pod_cidr                 = var.net_profile_pod_cidr
  net_profile_service_cidr             = var.net_profile_service_cidr
  net_profile_dns_service_ip           = var.net_profile_dns_service_ip
  network_ip_versions                  = var.network_ip_versions
  network_plugin_mode                  = var.network_plugin_mode
  only_critical_addons_enabled         = var.only_critical_addons_enabled
  rbac_aad_tenant_id                   = var.rbac_aad_tenant_id
  rbac_aad_azure_rbac_enabled          = var.rbac_aad_azure_rbac_enabled
  workload_identity_enabled            = var.workload_identity_enabled
}