
replicas: 2

controller:
  env:
    - name: CLUSTER_NAME
      value: "${aks_name}"
    - name: CLUSTER_ENDPOINT
      value: "${cluster_fqdn}"
    - name: KUBELET_BOOTSTRAP_TOKEN
      value: "${bootstrap_token}"
    - name: SSH_PUBLIC_KEY
      value: "${ssh_public_key}"
    - name: NETWORK_PLUGIN
      value: "${network_plugin}"
    - name: NETWORK_PLUGIN_MODE
      value: "${network_plugin_mode}"
    - name: NETWORK_POLICY
      value: "${network_policy}"
    - name: VNET_SUBNET_ID
      value: "${vnet_subnet_id}"
    - name: VNET_GUID
      value: "${vnet_guid}"
    - name: NODE_IDENTITIES
      value: "${kubelet_identity}"

    # Azure client settings
    - name: ARM_SUBSCRIPTION_ID
      value: "${azure_subscription_id}"
    - name: LOCATION
      value: "${location}"
    - name: KUBELET_IDENTITY_CLIENT_ID
      value: ""
    - name: AZURE_NODE_RESOURCE_GROUP
      value: "${azure_resource_group}"

    # managed karpenter settings
    - name: USE_SIG
      value: "false"
    - name: SIG_ACCESS_TOKEN_SERVER_URL
      value: ""
    - name: SIG_ACCESS_TOKEN_SCOPE
      value: ""
    - name: SIG_SUBSCRIPTION_ID
      value: ""

serviceAccount:
  name: "${karpenter_service_account_name}"
  annotations:
    azure.workload.identity/client-id: "${karpenter_user_assigned_client_id}"

podLabels:
  azure.workload.identity/use: "true"

logLevel: "${log_level}"

settings:
  spotToSpotConsolidation: true