{{- range $roleName, $group := .Values.clusterroleGroups }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $roleName | lower | replace "_" "-" | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $roleName | quote }}
subjects:
  - kind: Group
    name: {{ $group.id | quote }}
    apiGroup: rbac.authorization.k8s.io
---
{{- end }}
